PSPSDK: Interface to the LoadCoreForKernel library.
Interface to the LoadCoreForKernel library.
Data Structures
struct SceModule
Describes a module.
struct SceLibraryEntryTable
Defines a library and its exported functions and variables.
struct SceLibraryStubTable
Specifies a library and a set of imports from that library.
Typedefs
typedef struct SceLibraryEntryTable SceLibraryEntryTable
Defines a library and its exported functions and variables.
typedef struct SceLibraryStubTable SceLibraryStubTable
Specifies a library and a set of imports from that library.
Functions
struct SceModule __attribute__ ((packed)) SceModule
Describes a module.
SceModule * sceKernelFindModuleByName (const char *modname)
Find a module by it's name.
SceModule * sceKernelFindModuleByAddress (unsigned int addr)
Find a module from an address.
SceModule * sceKernelFindModuleByUID (SceUID modid)
Find a module by it's UID.
int sceKernelModuleCount (void)
Return the count of loaded modules.
void sceKernelIcacheClearAll (void)
Invalidate the CPU's instruction cache.
Detailed Description
Typedef Documentation
SceLibraryEntryTable
typedef struct SceLibraryEntryTable SceLibraryEntryTable
Defines a library and its exported functions and variables.
Use the len member to determine the real size of the table (size = len * 4).
SceLibraryStubTable
typedef struct SceLibraryStubTable SceLibraryStubTable
Specifies a library and a set of imports from that library.
Use the len member to determine the real size of the table (size = len * 4).
Function Documentation
__attribute__()
struct SceModule __attribute__ ((packed))
Describes a module.
This structure could change in future firmware revisions.
sceKernelFindModuleByAddress()
SceModule* sceKernelFindModuleByAddress (unsigned int addr)
Find a module from an address.
Parameters
addr - Address somewhere within the module.
Returns
Pointer to the SceModule structure if found, otherwise NULL.
sceKernelFindModuleByName()
SceModule* sceKernelFindModuleByName (const char * modname)
Find a module by it's name.
Parameters
modname - The name of the module.
Returns
Pointer to the SceModule structure if found, otherwise NULL.
sceKernelFindModuleByUID()
SceModule* sceKernelFindModuleByUID (SceUID modid)
Find a module by it's UID.
Parameters
modid - The UID of the module.
Returns
Pointer to the SceModule structure if found, otherwise NULL.
Referenced by pspSdkFixupImports(), and pspSdkQueryModuleInfoV1().
sceKernelIcacheClearAll()
void sceKernelIcacheClearAll (void)
Invalidate the CPU's instruction cache.
sceKernelModuleCount()
int sceKernelModuleCount (void)
Return the count of loaded modules.
Returns
The count of loaded modules.
Referenced by pspSdkGetModuleIdList().