PSPSDK: gu/guInternal.h File Reference
guInternal.h File Reference
#include "pspgu.h"
Data Structures
struct GuSettings
struct GuDisplayList
struct GuContext
struct GuDrawBuffer
struct GuLightSettings
Typedefs
typedef void(* GuCallback) (int)
Functions
void sendCommandi (int cmd, int argument)
void sendCommandiStall (int cmd, int argument)
void sendCommandf (int cmd, float argument)
void callbackSig (int id, void *arg)
void callbackFin (int id, void *arg)
void resetValues ()
Variables
unsigned int gu_current_frame
GuContext gu_contexts [3]
int ge_list_executed [2]
void * ge_edram_address
GuSettings gu_settings
GuDisplayList * gu_list
int gu_curr_context
int gu_init
int gu_display_on
int gu_call_mode
int gu_states
GuDrawBuffer gu_draw_buffer
unsigned int * gu_object_stack []
int gu_object_stack_depth
GuLightSettings light_settings [4]
Typedef Documentation
GuCallback
typedef void(* GuCallback) (int)
Function Documentation
callbackFin()
void callbackFin (int id, void * arg)
References GuSettings::fin.
Referenced by sceGuInit().
callbackSig()
void callbackSig (int id, void * arg)
References GuSettings::kernel_event_flag, sceKernelSetEventFlag(), GuSettings::sig, GuSettings::signal_history, and GuSettings::signal_offset.
Referenced by sceGuInit().
resetValues()
void resetValues ()
References GuContext::clear_color, GuContext::clear_depth, GuContext::clear_stencil, GuDrawBuffer::depth_buffer, GuContext::depth_offset, GuDrawBuffer::depth_width, GuDrawBuffer::disp_buffer, GuContext::far_plane, GuSettings::fin, GuContext::fragment_2x, GuDrawBuffer::frame_buffer, GuDrawBuffer::frame_width, gu_call_mode, gu_contexts, gu_current_frame, gu_display_on, gu_draw_buffer, gu_init, gu_object_stack_depth, gu_settings, gu_states, GuDrawBuffer::height, i, GuContext::near_plane, GuDrawBuffer::pixel_size, GuContext::scissor_enable, GuContext::scissor_end, GuContext::scissor_start, GuSettings::sig, GuContext::sprite_mode, GuContext::texture_function, GuContext::texture_map_mode, GuContext::texture_mode, GuContext::texture_proj_map_mode, and GuDrawBuffer::width.
Referenced by sceGuInit().
sendCommandf()
void sendCommandf (int cmd, float argument)
References f, i, and sendCommandi().
Referenced by sceGuBoneMatrix(), sceGuDepthRange(), sceGuFog(), sceGuLight(), sceGuLightAtt(), sceGuLightSpot(), sceGuMorphWeight(), sceGuSendCommandf(), sceGuSetMatrix(), sceGuSpecular(), sceGuTexFlush(), sceGuTexOffset(), sceGuTexScale(), sceGuTexSlope(), and sceGuViewport().
sendCommandi()
void sendCommandi (int cmd, int argument)
References GuDisplayList::current, and gu_list.
Referenced by drawRegion(), sceGuAlphaFunc(), sceGuAmbient(), sceGuAmbientColor(), sceGuBeginObject(), sceGuBlendFunc(), sceGuBoneMatrix(), sceGuCallList(), sceGuClear(), sceGuClutLoad(), sceGuClutMode(), sceGuColorFunc(), sceGuColorMaterial(), sceGuCopyImage(), sceGuDepthBuffer(), sceGuDepthFunc(), sceGuDepthMask(), sceGuDepthRange(), sceGuDisable(), sceGuDrawArray(), sceGuDrawArrayN(), sceGuDrawBezier(), sceGuDrawBuffer(), sceGuDrawBufferList(), sceGuDrawSpline(), sceGuEnable(), sceGuEndObject(), sceGuFinish(), sceGuFinishId(), sceGuFog(), sceGuFrontFace(), sceGuLight(), sceGuLightColor(), sceGuLightMode(), sceGuLogicalOp(), sceGuMaterial(), sceGuModelColor(), sceGuOffset(), sceGuPatchDivide(), sceGuPatchFrontFace(), sceGuPatchPrim(), sceGuPixelMask(), sceGuScissor(), sceGuSendCommandi(), sceGuSetDither(), sceGuShadeModel(), sceGuSignal(), sceGuStart(), sceGuStencilFunc(), sceGuStencilOp(), sceGuTexEnvColor(), sceGuTexFilter(), sceGuTexFunc(), sceGuTexImage(), sceGuTexLevelMode(), sceGuTexMapMode(), sceGuTexMode(), sceGuTexProjMapMode(), sceGuTexSync(), sceGuTexWrap(), sendCommandf(), and sendCommandiStall().
sendCommandiStall()
void sendCommandiStall (int cmd, int argument)
References GuDisplayList::current, ge_list_executed, gu_curr_context, gu_list, gu_object_stack_depth, sceGeListUpdateStallAddr(), and sendCommandi().
Referenced by sceGuCallList(), sceGuDrawArray(), sceGuDrawArrayN(), sceGuFinish(), sceGuFinishId(), and sceGuSignal().
Variable Documentation
ge_edram_address
void* ge_edram_address extern
Referenced by sceGuDispBuffer(), sceGuDisplay(), sceGuInit(), and sceGuSwapBuffers().
ge_list_executed
int ge_list_executed[2] extern
Referenced by sceGuGetMemory(), sceGuInit(), sceGuSendList(), sceGuStart(), sceGuSync(), and sendCommandiStall().
gu_call_mode
int gu_call_mode extern
Referenced by resetValues(), sceGuCallList(), sceGuCallMode(), sceGuFinish(), and sceGuFinishId().
gu_contexts
GuContext gu_contexts[3] extern
Referenced by resetValues(), sceGuClear(), sceGuClearColor(), sceGuClearDepth(), sceGuClearStencil(), sceGuDepthOffset(), sceGuDepthRange(), sceGuDisable(), sceGuEnable(), sceGuFinish(), sceGuFinishId(), sceGuScissor(), sceGuStart(), sceGuTexFunc(), sceGuTexMapMode(), sceGuTexMode(), and sceGuTexProjMapMode().
gu_curr_context
int gu_curr_context extern
Referenced by sceGuClear(), sceGuClearColor(), sceGuClearDepth(), sceGuClearStencil(), sceGuDepthOffset(), sceGuDepthRange(), sceGuDisable(), sceGuEnable(), sceGuFinish(), sceGuFinishId(), sceGuGetMemory(), sceGuScissor(), sceGuStart(), sceGuTexFunc(), sceGuTexMapMode(), sceGuTexMode(), sceGuTexProjMapMode(), and sendCommandiStall().
gu_current_frame
unsigned int gu_current_frame extern
Referenced by resetValues(), and sceGuSwapBuffers().
gu_display_on
int gu_display_on extern
Referenced by resetValues(), sceGuDispBuffer(), sceGuDisplay(), and sceGuSwapBuffers().
gu_draw_buffer
GuDrawBuffer gu_draw_buffer extern
Referenced by resetValues(), sceGuClear(), sceGuDepthBuffer(), sceGuDisable(), sceGuDispBuffer(), sceGuDisplay(), sceGuDrawBuffer(), sceGuStart(), and sceGuSwapBuffers().
gu_init
int gu_init extern
Referenced by resetValues(), and sceGuStart().
gu_list
GuDisplayList* gu_list extern
Referenced by sceGuBeginObject(), sceGuCheckList(), sceGuEndObject(), sceGuFinish(), sceGuFinishId(), sceGuGetMemory(), sceGuStart(), sendCommandi(), and sendCommandiStall().
gu_object_stack
unsigned int* gu_object_stack[] extern
Referenced by sceGuBeginObject(), and sceGuEndObject().
gu_object_stack_depth
int gu_object_stack_depth extern
Referenced by resetValues(), sceGuBeginObject(), sceGuEndObject(), and sendCommandiStall().
gu_settings
GuSettings gu_settings extern
Referenced by guSwapBuffersBehaviour(), guSwapBuffersCallback(), resetValues(), sceGuInit(), sceGuSendList(), sceGuSetCallback(), sceGuStart(), sceGuSwapBuffers(), and sceGuTerm().
gu_states
int gu_states extern
Referenced by resetValues(), sceGuDisable(), sceGuEnable(), sceGuGetAllStatus(), and sceGuGetStatus().
light_settings
GuLightSettings light_settings[4] extern
Referenced by sceGuLight(), sceGuLightAtt(), sceGuLightColor(), and sceGuLightSpot().