PSPSDK: gu/sendCommand.c File Reference
sendCommand.c File Reference
#include "guInternal.h"
#include <pspkernel.h>
#include <pspge.h>
Functions
void sendCommandi (int cmd, int argument)
void sendCommandf (int cmd, float argument)
void sendCommandiStall (int cmd, int argument)
Function Documentation
sendCommandf()
void sendCommandf (int cmd, float argument)
References f, i, and sendCommandi().
Referenced by sceGuBoneMatrix(), sceGuDepthRange(), sceGuFog(), sceGuLight(), sceGuLightAtt(), sceGuLightSpot(), sceGuMorphWeight(), sceGuSendCommandf(), sceGuSetMatrix(), sceGuSpecular(), sceGuTexFlush(), sceGuTexOffset(), sceGuTexScale(), sceGuTexSlope(), and sceGuViewport().
sendCommandi()
void sendCommandi (int cmd, int argument)
References GuDisplayList::current, and gu_list.
Referenced by drawRegion(), sceGuAlphaFunc(), sceGuAmbient(), sceGuAmbientColor(), sceGuBeginObject(), sceGuBlendFunc(), sceGuBoneMatrix(), sceGuCallList(), sceGuClear(), sceGuClutLoad(), sceGuClutMode(), sceGuColorFunc(), sceGuColorMaterial(), sceGuCopyImage(), sceGuDepthBuffer(), sceGuDepthFunc(), sceGuDepthMask(), sceGuDepthRange(), sceGuDisable(), sceGuDrawArray(), sceGuDrawArrayN(), sceGuDrawBezier(), sceGuDrawBuffer(), sceGuDrawBufferList(), sceGuDrawSpline(), sceGuEnable(), sceGuEndObject(), sceGuFinish(), sceGuFinishId(), sceGuFog(), sceGuFrontFace(), sceGuLight(), sceGuLightColor(), sceGuLightMode(), sceGuLogicalOp(), sceGuMaterial(), sceGuModelColor(), sceGuOffset(), sceGuPatchDivide(), sceGuPatchFrontFace(), sceGuPatchPrim(), sceGuPixelMask(), sceGuScissor(), sceGuSendCommandi(), sceGuSetDither(), sceGuShadeModel(), sceGuSignal(), sceGuStart(), sceGuStencilFunc(), sceGuStencilOp(), sceGuTexEnvColor(), sceGuTexFilter(), sceGuTexFunc(), sceGuTexImage(), sceGuTexLevelMode(), sceGuTexMapMode(), sceGuTexMode(), sceGuTexProjMapMode(), sceGuTexSync(), sceGuTexWrap(), sendCommandf(), and sendCommandiStall().
sendCommandiStall()
void sendCommandiStall (int cmd, int argument)
References GuDisplayList::current, ge_list_executed, gu_curr_context, gu_list, gu_object_stack_depth, sceGeListUpdateStallAddr(), and sendCommandi().
Referenced by sceGuCallList(), sceGuDrawArray(), sceGuDrawArrayN(), sceGuFinish(), sceGuFinishId(), and sceGuSignal().